"""W4.0: generate a QNN model of controllable weight size, to find the HTP ceiling.

The open question this exists to answer: a prior measurement on this box found
NPU offload failing above roughly 5 GB of weights, but that came from
llama.cpp's ggml-hexagon backend. Whether the limit belongs to the HTP, its
driver, or that backend is unknown - and it bounds the entire NPU line.

So: emit a chain of MatMul layers whose total weight size is a parameter, run
it on HTP, and grow it until something breaks. A chain of `[1,D] x [D,D]`
matmuls is a reasonable stand-in for the dense layers of a transformer.

    python gen_matmul_model.py --dim 1024 --layers 8 --out <dir>

Produces `<name>.cpp` and `<name>.bin` in the SDK's converter format, ready for
`build_model_lib.ps1`. The .bin is a tar of raw tensors; object-generator turns
each into an object file exporting `_binary_obj_binary_<name>_raw_start`, which
is what the BINVARSTART macro in the generated .cpp resolves against.
"""

from __future__ import annotations

import argparse
import io
import pathlib
import struct
import tarfile

HEADER = '''//==============================================================================
// Generated by dragon/qnn/gen_matmul_model.py - do not hand-edit.
// {desc}
//==============================================================================

#include "QnnModel.hpp"
#include "QnnOpDef.h"

// Flag to determine if Backend should node validation for each opNode added
#define DO_GRAPH_NODE_VALIDATIONS 1

using namespace qnn_wrapper_api;
extern "C" {{
QNN_API
ModelError_t QnnModel_composeGraphs(Qnn_BackendHandle_t backendHandle,
                                    QNN_INTERFACE_VER_TYPE interface,
                                    Qnn_ContextHandle_t contextHandle,
                                    const GraphConfigInfo_t **graphsConfigInfo,
                                    const uint32_t numGraphsConfigInfo,
                                    GraphInfoPtr_t **graphsInfo,
                                    uint32_t *numGraphsInfo,
                                    bool debug,
                                    QnnLog_Callback_t logCallback,
                                    QnnLog_Level_t maxLogLevel) {{

  ModelError_t err = MODEL_NO_ERROR;

  /* model/graph for {name}*/
  QnnModel {name};
  const QnnGraph_Config_t **graphConfigs = nullptr;
  VALIDATE(getQnnGraphConfigFromInfo(
               "{name}", graphsConfigInfo, numGraphsConfigInfo, graphConfigs),
           err);
  VALIDATE({name}.initialize(backendHandle,
                             interface,
                             contextHandle,
                             "{name}",
                             debug,
                             DO_GRAPH_NODE_VALIDATIONS,
                             graphConfigs),
           err);
'''

TENSOR = '''  uint32_t dimensions_{tname}[] = {dims};
  VALIDATE({graph}.addTensor("{tname}",
               (Qnn_Tensor_t){{
                   .version = QNN_TENSOR_VERSION_1,
                   .v1      = {{.id             = 0,
                          .name           = "{tname}",
                          .type           = {ttype},
                          .dataFormat     = QNN_TENSOR_DATA_FORMAT_FLAT_BUFFER,
                          .dataType       = QNN_DATATYPE_FLOAT_32,
                          .quantizeParams = {{QNN_DEFINITION_UNDEFINED,
                                             QNN_QUANTIZATION_ENCODING_UNDEFINED,
                                             {{.scaleOffsetEncoding = {{.scale = 0.0f, .offset = 0}}}}}},
                          .rank           = {rank},
                          .dimensions     = dimensions_{tname},
                          .memType        = QNN_TENSORMEMTYPE_RAW,
                          .clientBuf      = {{{clientbuf}}}}}}}),
           err);
'''

NODE = '''  const char *inputs_{node}[] = {{"{a}", "{b}"}};
  VALIDATE({graph}.addNode(QNN_OPCONFIG_VERSION_1,
                           "{node}",
                           "qti.aisw",
                           QNN_OP_MAT_MUL,
                           nullptr,
                           0,
                           inputs_{node},
                           2,
                           outputs_{node},
                           1),
           err);
'''

FOOTER = '''  VALIDATE({name}.freeCachedTensors(), err);

  /* Add all models to array to get graphsInfo */
  QnnModel *models[] = {{&{name}}};
  uint32_t numModels = 1;

  VALIDATE(getGraphInfoFromModels(*models, numModels, graphsInfo), err);
  *numGraphsInfo = numModels;

  return err;

}} // PREPARE_GRAPHS

QNN_API
ModelError_t QnnModel_freeGraphsInfo(GraphInfoPtr_t **graphsInfo, uint32_t numGraphsInfo) {{
  return qnn_wrapper_api::freeGraphsInfo(graphsInfo, numGraphsInfo);
}} // FREEGRAPHSINFO
}}
'''


def build(dim: int, layers: int, name: str, out: pathlib.Path) -> tuple[pathlib.Path, pathlib.Path, int]:
    cpp: list[str] = []
    raws: dict[str, bytes] = {}
    weight_bytes = 0

    desc = f"{layers} MatMul layers, [1,{dim}] x [{dim},{dim}] fp32"
    cpp.append(HEADER.format(name=name, desc=desc))

    # Network input.
    cpp.append(
        TENSOR.format(
            graph=name, tname="input_0", dims=f"{{1, {dim}}}", rank=2,
            ttype="QNN_TENSOR_TYPE_APP_WRITE",
            clientbuf=".data = nullptr, .dataSize = 0",
        )
    )

    prev = "input_0"
    for i in range(layers):
        w = f"w_{i}"
        # Deterministic values, scaled by 1/sqrt(dim) so each layer roughly
        # PRESERVES magnitude.
        #
        # This scaling is not cosmetic. Without it a [1,D]x[D,D] layer amplifies
        # by about sqrt(D) times the typical weight, which at D=4096 is ~4.5x per
        # layer - so eight layers overflow into ~1e14 and sixteen are pure
        # garbage. A run like that still prints "Finished Executing Graphs" and
        # still produces a file, so it looks like a pass while making any
        # CPU-vs-HTP comparison meaningless. Measured on 2026-08-19: the 512 MiB
        # model disagreed 100% between backends for exactly this reason.
        scale = 1.0 / (dim ** 0.5)
        period = b"".join(
            struct.pack("<f", (((k % 17) - 8) / 8.0) * scale) for k in range(17)
        )
        total = dim * dim * 4
        buf = (period * (total // len(period) + 1))[:total]
        raws[w] = buf
        weight_bytes += len(buf)

        cpp.append(
            TENSOR.format(
                graph=name, tname=w, dims=f"{{{dim}, {dim}}}", rank=2,
                ttype="QNN_TENSOR_TYPE_STATIC",
                clientbuf=f".data = BINVARSTART({w}), .dataSize = BINLEN({w})",
            )
        )

        last = i == layers - 1
        out_name = "output_0" if last else f"h_{i}"
        out_type = "QNN_TENSOR_TYPE_APP_READ" if last else "QNN_TENSOR_TYPE_NATIVE"
        node = f"mm_{i}"
        # addNode takes the output tensor by value, so declare it inline.
        cpp.append(f"  uint32_t dimensions_{out_name}[] = {{1, {dim}}};\n")
        cpp.append(
            f"  Qnn_Tensor_t outputs_{node}[] = {{\n"
            f"      (Qnn_Tensor_t){{.version = QNN_TENSOR_VERSION_1,\n"
            f"                     .v1 = {{.id = 0,\n"
            f"                            .name = \"{out_name}\",\n"
            f"                            .type = {out_type},\n"
            f"                            .dataFormat = QNN_TENSOR_DATA_FORMAT_FLAT_BUFFER,\n"
            f"                            .dataType = QNN_DATATYPE_FLOAT_32,\n"
            f"                            .quantizeParams = {{QNN_DEFINITION_UNDEFINED,\n"
            f"                                               QNN_QUANTIZATION_ENCODING_UNDEFINED,\n"
            f"                                               {{.scaleOffsetEncoding = {{.scale = 0.0f, .offset = 0}}}}}},\n"
            f"                            .rank = 2,\n"
            f"                            .dimensions = dimensions_{out_name},\n"
            f"                            .memType = QNN_TENSORMEMTYPE_RAW,\n"
            f"                            .clientBuf = {{.data = nullptr, .dataSize = 0}}}}}}}};\n"
        )
        cpp.append(NODE.format(graph=name, node=node, a=prev, b=w))
        prev = out_name

    cpp.append(FOOTER.format(name=name))

    out.mkdir(parents=True, exist_ok=True)
    cpp_path = out / f"{name}.cpp"
    cpp_path.write_text("".join(cpp), encoding="utf-8")

    # The .bin is a plain tar of <tensor>.raw; the generator untars it into
    # obj/binary/ and hands the lot to object-generator.
    bin_path = out / f"{name}.bin"
    with tarfile.open(bin_path, "w") as tar:
        for tname, data in raws.items():
            info = tarfile.TarInfo(name=f"{tname}.raw")
            info.size = len(data)
            tar.addfile(info, io.BytesIO(data))

    return cpp_path, bin_path, weight_bytes


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--dim", type=int, default=1024)
    ap.add_argument("--layers", type=int, default=4)
    ap.add_argument("--name", default=None)
    ap.add_argument("--out", required=True)
    a = ap.parse_args()

    name = a.name or f"mm_d{a.dim}_l{a.layers}"
    cpp, binf, nbytes = build(a.dim, a.layers, name, pathlib.Path(a.out))
    print(f"{cpp}")
    print(f"{binf}")
    print(f"weights: {nbytes:,} bytes ({nbytes / 1024**2:.1f} MiB)")
    # A [1,D]x[D,D] matmul is 2*D*D flops; the chain is layers times that.
    print(f"flops/inference: {2 * a.dim * a.dim * a.layers / 1e6:.1f} MFLOP")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
